name: Python CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'  # Adjust based on your project's requirements

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run linter
    - name: Lint with pylint
      run: pylint --disable=R,C hello.py

    # Format code
    - name: Format with black
      run: black *.py

    # Run tests
    - name: Run tests
      run: python -m pytest -vv test_hello.py
